
import common.OpenPDF;
import dao.ConnectionProvider;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;

public class Record extends javax.swing.JFrame {

    public Record() {
        initComponents();
        try {
            Connection con = ConnectionProvider.getCon();
            PreparedStatement pst = con.prepareStatement("SELECT * FROM bill");
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) recordsTable.getModel();
            model.setRowCount(0);
            int srNo = 1;
            while (rs.next()) {
                String Date = rs.getString("billDate");
                int Id = rs.getInt("billId");
                float price = rs.getFloat("TotalPrice");
                String generated = rs.getString("generated");
                model.addRow(new Object[]{srNo, Date, Id, price, generated});
                srNo++;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsTable = new javax.swing.JTable();
        JTableHeader head = recordsTable.getTableHeader();
        head.setFont(new Font("Century gothic",Font.BOLD,18));
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setBackground(new java.awt.Color(255, 255, 0));
        title.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(204, 255, 255));
        title.setText("Records");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, -1, -1));

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signs-close-icon-png-removebg-pr.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1870, 10, -1, -1));
        getContentPane().add(separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 80, 1981, 10));

        recordsTable.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        recordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Sr.No", "Date", "Bill Number", "Total Amount", "Generated by"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        recordsTable.setAlignmentX(1.0F);
        recordsTable.setAlignmentY(1.0F);
        recordsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        recordsTable.setMinimumSize(new java.awt.Dimension(80, 100));
        recordsTable.setPreferredSize(new java.awt.Dimension(455, 455));
        recordsTable.setRowHeight(25);
        recordsTable.setShowGrid(true);
        recordsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(recordsTable);
        recordsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 170, 1410, 490));

        backButton.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        backButton.setForeground(new java.awt.Color(204, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design (3)_1.png"))); // NOI18N
        backButton.setText("Back");
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled design.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Do you really want to close the application?", "Select", JOptionPane.YES_NO_OPTION);
        if (option == 0)
            System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void recordsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordsTableMouseClicked
        // TODO add your handling code here:
        int i = recordsTable.getSelectedRow();
        TableModel model = recordsTable.getModel();
        String id = model.getValueAt(i, 2).toString();
        int Id = Integer.parseInt(id);
        OpenPDF.openById(Id);
    }//GEN-LAST:event_recordsTableMouseClicked

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Record().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable recordsTable;
    private javax.swing.JSeparator separator;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
